services:
 a1-landing:
    build: .
    container_name: a1_landing_app
    restart: always
    labels:
      - "traefik.enable=true"
      # Change 'a1.1lab.ai' to your actual domain
      - "traefik.http.routers.a1.rule=Host(`1true.ru`,`www.1true.ru`)"
      - "traefik.http.routers.a1.entrypoints=websecure"
      - "traefik.http.routers.a1.tls.tls=true"
      - "traefik.http.routers.a1.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
